# Generated by Django 6.0.6 on 2026-07-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='accounts_em_email_f76c05_idx',
            old_name='accounts_em_email_c9f3b1_idx',
        ),
    ]
