"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load variables from a .env file in the backend/ directory if present.
# Lets the same settings.py work across dev / staging / prod without edits.
load_dotenv(BASE_DIR / ".env")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# ──────────────────────────────────────────────────────────────────────────
# Google Sign-In (free alternative to emailed OTP codes — no domain or
# email provider needed at all). Get a Client ID at
# console.cloud.google.com → APIs & Services → Credentials → Create
# OAuth client ID → Web application. Add your frontend's exact origin
# (e.g. https://ai-engineering-studio-frontend.onrender.com) under
# "Authorized JavaScript origins". The frontend needs the SAME client ID
# as VITE_GOOGLE_CLIENT_ID — see frontend/.env.example.
# ──────────────────────────────────────────────────────────────────────────
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID", "")

# ──────────────────────────────────────────────────────────────────────────
# Email (OTP login codes are sent through this)
# ──────────────────────────────────────────────────────────────────────────
# Two ways to send real email, tried in this order:
#
# 1. RESEND (HTTP API, port 443) — set RESEND_API_KEY in backend/.env.
#    Use this on Render: Render's free tier blocks outbound SMTP ports
#    (587/465) entirely, so Gmail SMTP below fails with
#    "OSError: Network is unreachable" no matter what credentials/timeout
#    you set. Resend sends over plain HTTPS, so it isn't affected.
#    Get a free key at resend.com → API Keys. You can send from
#    "onboarding@resend.dev" with zero setup, or verify your own domain
#    later and use RESEND_FROM_EMAIL.
#      RESEND_API_KEY=re_xxxxxxxxxxxx
#      RESEND_FROM_EMAIL=onboarding@resend.dev
#
# 2. GMAIL SMTP — fine for local dev / non-Render hosts that allow
#    outbound SMTP. Gmail rejects plain account-password logins, so
#    EMAIL_HOST_PASSWORD must be a Gmail "App Password":
#      Google Account → Security → 2-Step Verification → App passwords
#      EMAIL_HOST_USER=youraddress@gmail.com
#      EMAIL_HOST_PASSWORD=xxxx xxxx xxxx xxxx
#
# Neither set → falls back to printing the code to the console (dev only).
RESEND_API_KEY = os.getenv("RESEND_API_KEY", "")
RESEND_FROM_EMAIL = os.getenv("RESEND_FROM_EMAIL", "onboarding@resend.dev")

EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
# Without this, a blocked/slow SMTP connection hangs with no timeout until
# Gunicorn's own worker timeout kills the entire request.
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", RESEND_FROM_EMAIL if RESEND_API_KEY else EMAIL_HOST_USER)

# Only relevant when RESEND_API_KEY is NOT set — accounts/views.py checks
# RESEND_API_KEY first and calls Resend's HTTP API directly, bypassing
# Django's mail backend entirely. This EMAIL_BACKEND setting is just the
# SMTP/console fallback for that non-Resend path.
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "").strip() or (
    "django.core.mail.backends.smtp.EmailBackend"
    if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD
    else "django.core.mail.backends.console.EmailBackend"
)

# How long an emailed OTP stays valid for. See accounts/models.py.
OTP_EXPIRY_MINUTES = int(os.getenv("OTP_EXPIRY_MINUTES", "10"))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

# ──────────────────────────────────────────────────────────────────────────
# Deployment / hosts
# ──────────────────────────────────────────────────────────────────────────
# Previously hardcoded to [], which silently rejects every request once
# DEBUG=False in production (Django refuses unrecognized Host headers).
# Comma-separated env var so this works identically across dev/stage/prod
# without touching code, e.g.:
#   ALLOWED_HOSTS=api.example.com,www.example.com
ALLOWED_HOSTS = [
    h.strip() for h in os.getenv("ALLOWED_HOSTS", "").split(",") if h.strip()
]
if DEBUG and not ALLOWED_HOSTS:
    # Keep local `runserver` working out of the box without requiring an
    # env var for pure local dev.
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "architect",

    "accounts",
    "dashboard",
    "analyzer",
    "reports",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            # SQLite's default journal mode gives a writer exclusive
            # access — so this app's own progress polling (a GET request
            # on one thread, reading the analysis row every ~1s) could
            # block, and get blocked by, the analysis pipeline's own
            # status writes on another thread. WAL mode lets reads and
            # writes happen concurrently instead of serializing them.
            "init_command": "PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;",
            "timeout": 20,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ──────────────────────────────────────────────────────────────────────────
# CORS
# ──────────────────────────────────────────────────────────────────────────
# Previously hardcoded to localhost only, which would silently break the
# deployed frontend in production. Comma-separated env var, e.g.:
#   CORS_ALLOWED_ORIGINS=https://app.example.com,https://example.com
_default_cors = "http://localhost:5173,http://localhost:3000,http://127.0.0.1:3000"
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.getenv("CORS_ALLOWED_ORIGINS", _default_cors).split(",") if o.strip()
]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# ──────────────────────────────────────────────────────────────────────────
# Celery / Redis
# ──────────────────────────────────────────────────────────────────────────
# All values are overridable via environment variables so the same settings
# file works in dev (local Redis) and prod (managed Redis / Elasticache).

REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
USE_REDIS = os.getenv("USE_REDIS", "false").lower() == "true"

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", REDIS_URL)

# JSON only — never accept pickle, which can execute arbitrary code if the
# broker is ever compromised.
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Keep task results around for a day so the frontend can poll job progress
# even if it briefly disconnects.
CELERY_RESULT_EXPIRES = 60 * 60 * 24

# A single repo analysis can legitimately take minutes (clone + multiple
# analyzers). Give workers room before Celery kills the task.
CELERY_TASK_SOFT_TIME_LIMIT = 60 * 15   # 15 min — raises SoftTimeLimitExceeded
CELERY_TASK_TIME_LIMIT = 60 * 20        # 20 min — hard kill

# Surface task progress/state changes promptly instead of batching.
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_SEND_SENT_EVENT = True
CELERY_WORKER_SEND_TASK_EVENTS = True

# Avoid one slow analysis hogging a worker process indefinitely; recycle
# workers periodically to guard against memory creep from repeated clones.
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Route analysis jobs onto a dedicated queue so they can be scaled
# independently of lighter-weight maintenance tasks (cache cleanup, etc.).
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_ROUTES = {
    "analyzer.tasks.run_repository_analysis": {"queue": "analysis"},
    "analyzer.tasks.clone_repository_task": {"queue": "analysis"},
    "analyzer.tasks.generate_export_task": {"queue": "exports"},
}

# When Redis isn't available (no broker), run Celery tasks synchronously
# in-process instead of dispatching them to a worker. `.delay()` calls
# behave like a normal function call — analysis still works, it just
# blocks the request until the analysis finishes instead of running in
# the background. No separate `celery worker` process is needed in this
# mode.
if not USE_REDIS:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True


# ──────────────────────────────────────────────────────────────────────────
# Cache (used for repository GitHub-API metadata + commit-SHA cache lookups)
# ──────────────────────────────────────────────────────────────────────────

if USE_REDIS:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "TIMEOUT": 60 * 30,  # 30 minutes default
        }
    }
else:
    # No Redis available — fall back to Django's built-in in-process cache.
    # Fine for local dev; just means the cache doesn't persist across
    # `runserver` restarts and isn't shared across multiple processes.
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "ai-studio-locmem",
            "TIMEOUT": 60 * 30,
        }
    }

# ──────────────────────────────────────────────────────────────────────────
# Django REST Framework — token auth + per-user isolation
# ──────────────────────────────────────────────────────────────────────────
# Every /api/ endpoint (aside from plain Django views like /api/system/
# status/, and the intentionally-public badge endpoint) requires a valid
# auth token by default, and views additionally filter querysets by
# request.user so one account can never see another's analyses. See
# analyzer/throttles.py for the scan-specific rate limits referenced below.

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "basic_scan": "20/hour",
        "deep_scan": "5/hour",
        # OTP login endpoints — see accounts/throttles.py.
        "otp_request": "5/hour",
        "otp_verify": "20/hour",
        # Public read-only badge endpoint — see analyzer/badge_view.py.
        "badge": "60/hour",
    },
}

# ──────────────────────────────────────────────────────────────────────────
# Production security hardening
# ──────────────────────────────────────────────────────────────────────────
# All no-ops in local dev (DEBUG=True) and only take effect once DEBUG is
# False, which is when a real reverse proxy / TLS terminator is assumed to
# be in front of this app. Set behind a load balancer that already
# terminates TLS? Also set SECURE_PROXY_SSL_HEADER via env if needed.
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True") == "True"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

    # Needed for Django's own CSRF checks (admin, session-auth endpoints)
    # when the frontend and API live on different subdomains/ports behind
    # HTTPS. Comma-separated, e.g.:
    #   CSRF_TRUSTED_ORIGINS=https://app.example.com
    CSRF_TRUSTED_ORIGINS = [
        o.strip() for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
    ]