"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load variables from a .env file in the backend/ directory if present.
# Lets the same settings.py work across dev / staging / prod without edits.
load_dotenv(BASE_DIR / ".env")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "architect",

    "accounts",
    "dashboard",
    "analyzer",
    "reports",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            # SQLite's default journal mode gives a writer exclusive
            # access — so this app's own progress polling (a GET request
            # on one thread, reading the analysis row every ~1s) could
            # block, and get blocked by, the analysis pipeline's own
            # status writes on another thread. Since the eager-mode
            # pipeline updates progress ~7 times per run and each write
            # could queue behind an in-flight poll (or vice versa), that
            # contention was invisible to per-stage timing yet accounted
            # for the bulk of total wall-clock time (~20s of a 22s run
            # was unaccounted for by any actual analysis work).
            #
            # WAL (Write-Ahead Logging) mode lets reads and writes happen
            # concurrently instead of serializing them — this is the
            # standard fix for exactly this pattern. `timeout` (seconds)
            # is a safety net: how long to wait for a lock before raising
            # "database is locked" instead of hanging silently.
            "init_command": "PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;",
            "timeout": 20,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# ──────────────────────────────────────────────────────────────────────────
# Celery / Redis
# ──────────────────────────────────────────────────────────────────────────
# All values are overridable via environment variables so the same settings
# file works in dev (local Redis) and prod (managed Redis / Elasticache).

REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
USE_REDIS = os.getenv("USE_REDIS", "false").lower() == "true"

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", REDIS_URL)

# JSON only — never accept pickle, which can execute arbitrary code if the
# broker is ever compromised.
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Keep task results around for a day so the frontend can poll job progress
# even if it briefly disconnects.
CELERY_RESULT_EXPIRES = 60 * 60 * 24

# A single repo analysis can legitimately take minutes (clone + multiple
# analyzers). Give workers room before Celery kills the task.
CELERY_TASK_SOFT_TIME_LIMIT = 60 * 15   # 15 min — raises SoftTimeLimitExceeded
CELERY_TASK_TIME_LIMIT = 60 * 20        # 20 min — hard kill

# Surface task progress/state changes promptly instead of batching.
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_SEND_SENT_EVENT = True
CELERY_WORKER_SEND_TASK_EVENTS = True

# Avoid one slow analysis hogging a worker process indefinitely; recycle
# workers periodically to guard against memory creep from repeated clones.
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Route analysis jobs onto a dedicated queue so they can be scaled
# independently of lighter-weight maintenance tasks (cache cleanup, etc.).
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_ROUTES = {
    "analyzer.tasks.run_repository_analysis": {"queue": "analysis"},
    "analyzer.tasks.clone_repository_task": {"queue": "analysis"},
    "analyzer.tasks.generate_export_task": {"queue": "exports"},
}

# When Redis isn't available (no broker), run Celery tasks synchronously
# in-process instead of dispatching them to a worker. `.delay()` calls
# behave like a normal function call — analysis still works, it just
# blocks the request until the analysis finishes instead of running in
# the background. No separate `celery worker` process is needed in this
# mode.
if not USE_REDIS:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True


# ──────────────────────────────────────────────────────────────────────────
# Cache (used for repository GitHub-API metadata + commit-SHA cache lookups)
# ──────────────────────────────────────────────────────────────────────────

if USE_REDIS:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "TIMEOUT": 60 * 30,  # 30 minutes default
        }
    }
else:
    # No Redis available — fall back to Django's built-in in-process cache.
    # Fine for local dev; just means the cache doesn't persist across
    # `runserver` restarts and isn't shared across multiple processes.
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "ai-studio-locmem",
            "TIMEOUT": 60 * 30,
        }
    }

# ──────────────────────────────────────────────────────────────────────────
# Django REST Framework — token auth + per-user isolation
# ──────────────────────────────────────────────────────────────────────────
# Every /api/ endpoint (aside from plain Django views like /api/system/
# status/) requires a valid auth token by default, and views additionally
# filter querysets by request.user so one account can never see another's
# analyses. See analyzer/throttles.py for the scan-specific rate limits
# referenced below.

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "basic_scan": "20/hour",
        "deep_scan": "5/hour",
    },
}