# Generated by Django 6.0.6 on 2026-06-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField()),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('repository_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('file_count', models.IntegerField(default=0)),
                ('folder_count', models.IntegerField(default=0)),
                ('has_readme', models.BooleanField(default=False)),
                ('has_docker', models.BooleanField(default=False)),
                ('has_requirements', models.BooleanField(default=False)),
                ('has_package_json', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_scanned', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
