# Generated by Django 6.0.6 on 2026-06-30 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_async_job_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='repositoryanalysis',
            new_name='analyzer_re_repo_ur_f112bb_idx',
            old_name='analyzer_re_repo_ur_5e0f8a_idx',
        ),
    ]
