# Generated by Django 6.0.6 on 2026-06-28 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture_type', models.CharField(blank=True, max_length=200)),
                ('frontend', models.JSONField(blank=True, default=list)),
                ('backend', models.JSONField(blank=True, default=list)),
                ('databases', models.JSONField(blank=True, default=list)),
                ('authentication', models.JSONField(blank=True, default=list)),
                ('api_type', models.JSONField(blank=True, default=list)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='architect_report', to='analyzer.repositoryanalysis')),
            ],
        ),
    ]
